import { Product, Testimonial, FAQ, ServiceItem, SiteSettings } from './types';

export const defaultSiteSettings: SiteSettings = {
  id: 1,
  tagline: 'Jasa Pembuatan Website Profesional & Elegan untuk Pertumbuhan Bisnis Anda',
  advantages: [
    'Desain Mewah & Presisi — Tampilan elegan yang langsung meningkatkan kepercayaan calon klien.',
    'Loading Cepat & Muncul di Google — Pengunjung gak kabur karena loading lama, dan bisnis Anda lebih mudah ditemukan di Google.',
    'Langsung Closing via WhatsApp — Tombol konsultasi di setiap titik strategis untuk closing lebih cepat.',
    'Kelola Website Sendiri — Edit harga, foto, dan kontak kapan saja tanpa bantuan programmer.',
  ],
  whatsapp_number: '6281234567890',
  contact_email: 'halo@kydev.id',
  contact_address: 'Jakarta Selatan, DKI Jakarta, Indonesia',
};

export const defaultProducts: Product[] = [
  {
    id: 'prod-1',
    name: 'Landing Page Konversi Tinggi',
    slug: 'landing-page-konversi-tinggi',
    short_description: 'Satu halaman fokus konversi untuk promosi produk, jasa, event, atau iklan Google/Meta Ads.',
    full_description: 'Paket Landing Page dirancang khusus untuk memaksimalkan ROI iklan dan promosi Anda. Menggunakan copywriting persuasif, alur visual terarah, CTA WhatsApp terintegrasi, dan loading kilat di bawah 1 detik.',
    price: 1500000,
    harga_maks: null,
    show_price: true,
    is_starting_price: false,
    button_text: 'Pilih Paket',
    button_link: null,
    features: [
      'Desain Custom 1 Halaman Premium',
      'Copywriting & Alur Konversi Lead',
      'Direct WhatsApp Order Integration',
      'Mobile First & Responsive 100%',
      'Gratis Domain .com & Hosting 1 Tahun',
      'Revisi sampai tuntas & Garansi Maintenance',
    ],
    image_url: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=800&auto=format&fit=crop',
    is_visible: true,
    sort_order: 1,
  },
  {
    id: 'prod-2',
    name: 'Company Profile Perusahaan',
    slug: 'company-profile-perusahaan',
    short_description: 'Website profil bisnis multi-halaman untuk membangun kredibilitas korporat dan memenangkan tender.',
    full_description: 'Solusi ideal bagi perusahaan berkembang dan korporat yang membutuhkan etalase digital bonafide. Memuat halaman Beranda, Tentang Kami, Layanan, Portofolio Proyek, Tim, dan Kontak terintegrasi.',
    price: 3500000,
    harga_maks: null,
    show_price: true,
    is_starting_price: false,
    button_text: 'Pilih Paket',
    button_link: null,
    features: [
      '5–7 Halaman Struktur Lengkap',
      'Desain Minimalis Elegan Standar Internasional',
      'Dashboard CMS Admin untuk Update Konten',
      'Email Profesional Bisnis (nama@perusahaan.com)',
      'Optimasi SEO On-Page Google',
      'Keamanan SSL & Backup Otomatis',
    ],
    image_url: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=800&auto=format&fit=crop',
    is_visible: true,
    sort_order: 2,
  },
  {
    id: 'prod-3',
    name: 'Website Katalog & Toko Online',
    slug: 'website-katalog-toko-online',
    short_description: 'Etalase produk interaktif dengan sistem pemesanan langsung ke WhatsApp admin toko.',
    full_description: 'Tampilkan produk Anda secara rapi, modern, dan informatif. Dilengkapi filter kategori, pencarian cepat, galeri foto produk high-res, dan tombol Checkout ke WhatsApp otomatis dengan ringkasan pesanan.',
    price: 4500000,
    harga_maks: null,
    show_price: true,
    is_starting_price: false,
    button_text: 'Pilih Paket',
    button_link: null,
    features: [
      'Katalog Produk Unlimited & Kategori',
      'Checkout WhatsApp dengan Template Otomatis',
      'Dashboard Admin Kelola Produk & Stok',
      'Bisa Tampilkan/Sembunyikan Harga',
      'Integrasi Media Sosial & Google Maps',
      'Panduan Video Pengelolaan Website',
    ],
    image_url: 'https://images.unsplash.com/photo-1472851294608-062f824d29cc?q=80&w=800&auto=format&fit=crop',
    is_visible: true,
    sort_order: 3,
  },
  {
    id: 'prod-4',
    name: 'Custom Web Application & Portal',
    slug: 'custom-web-application-portal',
    short_description: 'Sistem web kustom khusus dengan fitur database, role user/member, dan workflow internal.',
    full_description: 'Untuk kebutuhan bisnis yang memerlukan alur kerja khusus, sistem reservasi, portal membership klien, atau dashboard analitik khusus bisnis Anda menggunakan Next.js dan Supabase.',
    price: 8000000,
    harga_maks: null,
    show_price: false,
    is_starting_price: true,
    button_text: 'Konsultasi Kustom',
    button_link: null,
    features: [
      'Arsitektur Database Khusus (Supabase)',
      'Sistem Login & Role Pengguna',
      'Dashboard Interaktif Realtime',
      'Integrasi API Pihak Ketiga',
      'High Scalability & Cloud Deployment',
      'Full Source Code & Dokumentasi Teknis',
    ],
    image_url: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=800&auto=format&fit=crop',
    is_visible: true,
    sort_order: 4,
  },
];

export const defaultTestimonials: Testimonial[] = [
  {
    id: 'test-1',
    customer_name: 'Budi Hartanto',
    company: 'PT Sinergi Abadi Teknik',
    source: 'Klien Company Profile',
    content: 'Sebelumnya website kami terkesan kaku dan lambat. Setelah dibuatkan ulang oleh KyDev dengan tampilan baru yang bersih dan modern, klien dari luar kota langsung percaya dan tender proyek kami tembus!',
    rating: 5,
    image_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=300&auto=format&fit=crop',
    is_visible: true,
    sort_order: 1,
  },
  {
    id: 'test-2',
    customer_name: 'Clarissa Natalia',
    company: 'Lumiere Beauty Studio',
    source: 'Klien Landing Page Promo',
    content: 'Desainnya bener-bener mewah, estetik banget! Tombol WhatsApp-nya terbukti bikin pengunjung langsung chat tanpa bingung. Konversi booking salon kami naik lebih dari 40%.',
    rating: 5,
    image_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=300&auto=format&fit=crop',
    is_visible: true,
    sort_order: 2,
  },
  {
    id: 'test-3',
    customer_name: 'Reza Fahlevi',
    company: 'UrbanKicks Sneakers',
    source: 'Klien Katalog Online',
    content: 'Sangat puas dengan KyDev! Dashboard adminnya mudah banget dipakai, upload foto produk tinggal klik-klik dari HP pun bisa. Adminnya fast response dan bantu sampai live.',
    rating: 5,
    image_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=300&auto=format&fit=crop',
    is_visible: true,
    sort_order: 3,
  },
];

export const defaultFaqs: FAQ[] = [
  {
    id: 'faq-1',
    question: 'Berapa lama proses pembuatan website di KyDev?',
    answer: 'Untuk Landing Page rata-rata pengerjaan 3–5 hari kerja. Untuk Company Profile dan Katalog Produk berkisar antara 7–14 hari kerja setelah materi dan konten kami terima lengkap.',
    is_visible: true,
    sort_order: 1,
  },
  {
    id: 'faq-2',
    question: 'Apakah saya bisa mengubah sendiri tulisan dan foto produk setelah jadi?',
    answer: 'Tentu saja! Kami menyediakan Dashboard Admin khusus yang ramah pengguna. Anda bisa mengubah teks, nomor WhatsApp, kontak, upload foto produk baru, dan mengatur testimoni kapan saja tanpa perlu paham koding.',
    is_visible: true,
    sort_order: 2,
  },
  {
    id: 'faq-3',
    question: 'Apakah sudah termasuk domain dan hosting?',
    answer: 'Ya, semua paket pembuatan website di KyDev sudah termasuk domain utama (.com) dan cloud hosting berkecepatan tinggi selama 1 tahun pertama, lengkap dengan sertifikat keamanan SSL gratis.',
    is_visible: true,
    sort_order: 3,
  },
  {
    id: 'faq-4',
    question: 'Bagaimana alur pemesanan dan pembayarannya?',
    answer: 'Cukup klik tombol Konsultasi WhatsApp di website ini. Kami akan berdiskusi mengenai kebutuhan Anda, menyiapkan kesepakatan spesifikasi, DP 50%, proses pengerjaan dan review, lalu pelunasan saat website siap live.',
    is_visible: true,
    sort_order: 4,
  },
  {
    id: 'faq-5',
    question: 'Apakah website ini responsif di layar HP dan tablet?',
    answer: 'Pasti. Kami menerapkan pendekatan Mobile-First dengan standar desain modern. Website Anda akan tampil proporsional, tajam, dan sangat nyaman diakses di smartphone, tablet, maupun layar monitor laptop.',
    is_visible: true,
    sort_order: 5,
  },
];

export const defaultServices: ServiceItem[] = [
  { id: 'srv-1', name: 'Jasa Pembuatan Landing Page', is_visible: true, sort_order: 1 },
  { id: 'srv-2', name: 'Jasa Pembuatan Company Profile', is_visible: true, sort_order: 2 },
  { id: 'srv-3', name: 'Website Katalog & Toko Online', is_visible: true, sort_order: 3 },
  { id: 'srv-4', name: 'Pengembangan Custom Web App', is_visible: true, sort_order: 4 },
  { id: 'srv-5', name: 'Redesain Website Modern', is_visible: true, sort_order: 5 },
];

export const defaultPortfolios: import('./types').PortfolioProject[] = [
  {
    id: 'port-1',
    title: 'Kasir Cerdas POS',
    slug: 'kasir-cerdas-pos',
    category: 'Aplikasi Kasir',
    description: 'Aplikasi Point of Sale cerdas berbasis web & PWA dengan pencatatan transaksi kilat, cetak struk bluetooth, dan rekap omzet harian otomatis.',
    features: [
      'Pencatatan Penjualan Cepat & Scan Barcode',
      'Cetak Struk Kasir Bluetooth & Thermal',
      'Manajemen Stok & Notifikasi Barang Habis',
      'Laporan Laba Rugi & Rekap Kas Harian',
      'Bisa Diakses dari HP, Tablet, & Laptop',
    ],
    image_url: 'https://images.unsplash.com/photo-1556742049-0a67c5574f73?q=80&w=800&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1556742049-0a67c5574f73?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1556740738-b6a63e27c4df?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1556742502-ec7c0e9f34b1?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=800&auto=format&fit=crop',
    ],
    has_live_url: true,
    live_url: 'https://demo-kasir.kydev.id',
    is_featured: true,
    is_visible: true,
    sort_order: 1,
  },
  {
    id: 'port-2',
    title: 'Kasir Warkop Modern',
    slug: 'kasir-warkop-modern',
    category: 'F&B & Warkop',
    description: 'Sistem kasir ringkas yang dirancang khusus untuk warkop, angkringan, dan kedai kopi dengan navigasi 1-klik tanpa ribet.',
    features: [
      'Menu Cepat 1-Klik Khusus Minuman & Makanan',
      'Hitung Total & Kembalian Otomatis',
      'Dukungan Multi Kasir / Shift Karyawan',
      'Kirim Bukti Pembayaran via WhatsApp Klien',
    ],
    image_url: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?q=80&w=800&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop',
    ],
    has_live_url: false,
    live_url: '',
    is_featured: false,
    is_visible: true,
    sort_order: 2,
  },
  {
    id: 'port-3',
    title: 'LoanLoanDRY — Sistem Kasir Laundry',
    slug: 'loanloandry-kasir-laundry',
    category: 'Jasa Laundry',
    description: 'Software manajemen usaha laundry kiloan & satuan dengan notifikasi status cucian siap ambil otomatis langsung ke WhatsApp pelanggan.',
    features: [
      'Pencatatan Cucian Kiloan, Bedcover, & Satuan',
      'Nomor Rak & Estimasi Selesai Otomatis',
      'Kirim Notifikasi WA "Cucian Siap Ambil"',
      'Laporan Pemasukan Harian & Bulanan',
    ],
    image_url: 'https://images.unsplash.com/photo-1545173168-9f1907e80789?q=80&w=800&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1545173168-9f1907e80789?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1521656693074-0ef32e80a5d5?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1517677208171-0bc6725a3e60?q=80&w=800&auto=format&fit=crop',
    ],
    has_live_url: false,
    live_url: '',
    is_featured: false,
    is_visible: true,
    sort_order: 3,
  },
  {
    id: 'port-4',
    title: 'Maximum Gym & Fitness Club',
    slug: 'maximum-gym-fitness',
    category: 'Gym & Olahraga',
    description: 'Website resmi fitness center dengan etalase paket membership, jadwal kelas instruktur, dan sistem pendaftaran member baru.',
    features: [
      'Katalog Paket Member Bulanan & Tahunan',
      'Jadwal Kelas Personal Trainer Interaktif',
      'Integrasi Tombol WhatsApp Gabung Member',
      'Galeri Fasilitas Gym High Definition',
    ],
    image_url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=800&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?q=80&w=800&auto=format&fit=crop',
    ],
    has_live_url: true,
    live_url: 'https://maximum-gym.kydev.id',
    is_featured: false,
    is_visible: true,
    sort_order: 4,
  },
  {
    id: 'port-5',
    title: 'CAVEEE — Resto & Specialty Coffee',
    slug: 'caveee-cafe-resto',
    category: 'Cafe & Resto',
    description: 'Website company profile cafe modern bergaya minimalis dengan buku menu digital interaktif dan reservasi meja instan.',
    features: [
      'Buku Menu Makanan & Minuman Digital QR',
      'Formulir Reservasi Meja ke WhatsApp',
      'Integrasi Lokasi Google Maps & Jam Operasional',
      'Estetika Gelap & Elegan Premium',
    ],
    image_url: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?q=80&w=800&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1554118811-1e0d58224f24?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1509042239860-f550ce710b93?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1442512595331-e89e73853f31?q=80&w=800&auto=format&fit=crop',
    ],
    has_live_url: false,
    live_url: '',
    is_featured: false,
    is_visible: true,
    sort_order: 5,
  },
  {
    id: 'port-6',
    title: 'Warehouse Management System',
    slug: 'warehouse-management-system',
    category: 'Aplikasi Bisnis',
    description: 'Sistem manajemen pergudangan untuk kontrol stok barang masuk, keluar, mutasi lokasi rak, dan audit opname realtime.',
    features: [
      'Manajemen Inbound, Outbound, & Transfer Stok',
      'Sistem Nomor Batch & Barcode Tracking',
      'Dashboard Analitik Level Stok Kritis',
      'Cetak Surat Jalan & Label Barcode',
    ],
    image_url: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?q=80&w=800&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1553413077-190dd305871c?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1616401784845-180882ba9ba8?q=80&w=800&auto=format&fit=crop',
    ],
    has_live_url: false,
    live_url: '',
    is_featured: false,
    is_visible: true,
    sort_order: 6,
  },
];
